export interface Tool {
  id: string;
  title: string;
  desc: string;
  href: string;
  icon: string;
  category: string;
  accent: 'teal' | 'blue' | 'peach' | 'red' | 'mauve' | 'green' | 'amber';
  status: 'Active' | 'Planned';
  active: boolean;
  keywords: string[];
  priority?: string;
  changefreq?: string;
}

export const tools: Tool[] = [
  {
    id: 'cdn-validator',
    icon: '🖼️',
    status: 'Active',
    category: 'Validation',
    accent: 'teal',
    title: 'Image CDN Validator',
    desc: 'Bulk-check image URLs by provider, response code, and Content-Type. Concurrent validation with edge CORS proxying.',
    href: '/cdn-validator',
    active: true,
    keywords: ['cdn', 'image', 'url', 'status', 'headers', 'cors', 'proxy', 'validator', 'check'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'api-tester',
    icon: '🌐',
    status: 'Active',
    category: 'HTTP',
    accent: 'blue',
    title: 'API Tester',
    desc: 'Browser-local HTTP client with custom methods, headers, body editor, and optional CORS proxy for cross-origin debugging.',
    href: '/api-tester',
    active: true,
    keywords: ['http', 'rest', 'api', 'fetch', 'curl', 'request', 'post', 'get', 'headers', 'cors'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'dns-lookup',
    icon: '🔍',
    status: 'Active',
    category: 'Network',
    accent: 'mauve',
    title: 'DNS Lookup',
    desc: 'Query public DNS-over-HTTPS resolvers for A, AAAA, MX, TXT, CNAME, and other record types.',
    href: '/dns-lookup',
    active: true,
    keywords: ['dns', 'doh', 'domain', 'ip', 'mx', 'txt', 'cname', 'ns', 'soa', 'lookup', 'records'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'text-extractor',
    icon: '🔗',
    status: 'Active',
    category: 'Text',
    accent: 'green',
    title: 'Text Extractor',
    desc: 'Paste logs, HTML, or markdown and extract URLs, emails, domains, or IP addresses with deduplication, sorting, and one-click copy.',
    href: '/text-extractor',
    active: true,
    keywords: ['extract', 'regex', 'urls', 'emails', 'domains', 'ip', 'deduplicate', 'sort', 'log'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'regex-playground',
    icon: '🧩',
    status: 'Active',
    category: 'Regex',
    accent: 'mauve',
    title: 'Regex Playground',
    desc: 'Test, visualize, and debug regular expressions in real-time. Includes syntax highlighting, match breakdowns, and group captures.',
    href: '/regex-playground',
    active: true,
    keywords: ['regex', 'regular expression', 'pattern', 'match', 'test', 'replace', 'groups'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'spreadsheet-viewer',
    icon: '📊',
    status: 'Active',
    category: 'Data',
    accent: 'green',
    title: 'Spreadsheet Viewer',
    desc: 'Open CSV, TSV, Excel, ODS, JSON, or Markdown tables locally. Sort, filter, paginate, and export to CSV.',
    href: '/spreadsheet-viewer',
    active: true,
    keywords: ['csv', 'excel', 'xlsx', 'sheet', 'table', 'tsv', 'ods', 'data', 'viewer', 'spreadsheet'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'markdown-editor',
    icon: '📝',
    status: 'Active',
    category: 'Writing',
    accent: 'blue',
    title: 'Markdown Editor',
    desc: 'Write Markdown with a live split-pane preview, formatting toolbar, and one-click HTML or .md export.',
    href: '/markdown-editor',
    active: true,
    keywords: ['markdown', 'md', 'preview', 'editor', 'html', 'write', 'document'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'ddos-simulator',
    icon: '🌩️',
    status: 'Active',
    category: 'Fun',
    accent: 'red',
    title: 'DDoS Simulator',
    desc: 'Farm a botnet by clicking the map, manage your trace, buy upgrades, and pwn 7 targets — or play defense against waves. 100% simulated.',
    href: '/ddos-simulator',
    active: true,
    keywords: ['ddos', 'botnet', 'simulate', 'attack', 'flood', 'game', 'defense', 'cyber'],
    priority: '0.7',
    changefreq: 'monthly',
  },
  {
    id: 'base64',
    icon: '🔤',
    status: 'Active',
    category: 'Encoding',
    accent: 'peach',
    title: 'Base64 Encoder / Decoder',
    desc: 'Encode text or files to Base64 and decode Base64 back to text, with URL-safe and data URI options.',
    href: '/base64',
    active: true,
    keywords: ['base64', 'encode', 'decode', 'data uri', 'binary', 'url safe', 'atob', 'btoa'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'json-formatter',
    icon: '📋',
    status: 'Active',
    category: 'Data',
    accent: 'blue',
    title: 'JSON Formatter',
    desc: 'Format, validate, and minify JSON with syntax highlighting, tree view, and statistics.',
    href: '/json-formatter',
    active: true,
    keywords: ['json', 'format', 'minify', 'validate', 'tree', 'prettify', 'beautify', 'syntax'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'uuid-generator',
    icon: '🆔',
    status: 'Active',
    category: 'Data',
    accent: 'green',
    title: 'UUID Generator',
    desc: 'Generate UUIDs v1, v4, and v7 entirely in your browser — no data leaves your device.',
    href: '/uuid-generator',
    active: true,
    keywords: ['uuid', 'guid', 'v1', 'v4', 'v7', 'random', 'identifier', 'generate', 'rfc4122'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'timestamp-converter',
    icon: '⏱',
    status: 'Active',
    category: 'Date/Time',
    accent: 'blue',
    title: 'Unix Timestamp Converter',
    desc: 'Convert between Unix timestamps, ISO 8601, UTC, and human-readable dates — supports seconds, milliseconds, and nanoseconds.',
    href: '/timestamp-converter',
    active: true,
    keywords: ['unix', 'timestamp', 'epoch', 'date', 'time', 'iso8601', 'utc', 'convert', 'timezone'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'hash-generator',
    icon: '🔒',
    status: 'Active',
    category: 'Security',
    accent: 'amber',
    title: 'Hash Generator',
    desc: 'Hash text or files with SHA-1, SHA-256, SHA-384, SHA-512, and MD5 — entirely in your browser via Web Crypto API.',
    href: '/hash-generator',
    active: true,
    keywords: ['hash', 'sha256', 'md5', 'sha1', 'sha512', 'sha384', 'crypto', 'digest', 'checksum'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'jwt-decoder',
    icon: '🔓',
    status: 'Active',
    category: 'Security',
    accent: 'mauve',
    title: 'JWT Decoder',
    desc: 'Decode JWT tokens and inspect header, payload, and signature — with registered claims analysis and expiration status.',
    href: '/jwt-decoder',
    active: true,
    keywords: ['jwt', 'token', 'decode', 'json web token', 'claims', 'auth', 'bearer', 'header', 'payload'],
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    id: 'html-encoder',
    icon: '🔡',
    status: 'Active',
    category: 'Encoding',
    accent: 'peach',
    title: 'HTML Entity Encoder',
    desc: 'Encode and decode HTML entities, escape text for safe insertion, and convert between named, numeric, and hex formats.',
    href: '/html-encoder',
    active: true,
    keywords: ['html', 'entity', 'entities', 'escape', 'unescape', 'encode', 'decode', 'special characters'],
    priority: '0.8',
    changefreq: 'monthly',
  },
];

export const categories = Array.from(new Set(tools.map(t => t.category)));
